apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: orion-deployment
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: orion
   spec:
     containers:
     - name: orion-container
       image: orion
#     nodeSelector:
#       TypeOfPod: orion
