apiVersion: v1
kind: Service
metadata:
  name: postgre-service
  labels:
    app: postgre
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgre
    tier: sql
  externalIPs:
    - 10.25.25.120
