kind: Service
apiVersion: v1
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
  - name: database
    protocol: TCP
    port: 5432
    targetPort: 5432
  externalIPs:
    - 10.25.25.100

