apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs
spec:
  capacity:
    storage: 9Go
  accessModes:
    - ReadWriteMany
  glusterfs:
    server: gluster-service
    path: "/volume-Mongo"
