apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: gitbucket-deployment
spec:
 replicas: 2
 template:
   metadata:
     labels:
       app: gitbucket
   spec:
     containers:
     - name: gitbucket-container
       image: f99aq8ove/gitbucket
#     nodeSelector:
#       TypeOfPod: gitbucket
