apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: gitbucket-deployment
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: gitbucket
   spec:
     containers:
     - name: gitbucket-container
       image: f99aq8ove/gitbucket
       env:
       - name: GITBUCKET_DB_URL
         value: jdbc:postgresql://postgresql-service/
       - name: GITBUCKET_DB_USER
         value: postgres
       - name: GITBUCKET_DB_PASSWORD
         value: superpostgres
#     nodeSelector:
#       TypeOfPod: gitbucket
