apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: gitlab-deployment
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: gitlab
   spec:
     containers:
     - name: gitlab-container
       image: gitlab/gitlab-ce:latest
     nodeSelector:
       TypeOfPod: GitLab
