apiVersion: v1
kind: ConfigMap
metadata:
 name: gitlab-configmap
data:
 # property-like keys
 #gitlab-rb-file-name: gitlabt
 # file-like keys
 gitlab.rb: |
   # Disable the built-in Postgres
   postgresql['enable'] = false
   # Fill in the values for database.yml
   gitlab_rails['db_adapter'] = 'postgresql'
   gitlab_rails['db_encoding'] = 'utf8'
   gitlab_rails['db_host'] = 'postgresql-service'
   gitlab_rails['db_name'] = 'gitlabhq_production'
   gitlab_rails['db_port'] = '5432'
   gitlab_rails['db_username'] = 'postgres'
   gitlab_rails['db_password'] = 'superpostgres'
   # Disable the built-in redis
   redis['enable'] = false
   gitlab_rails['redis_host'] = 'redis-service'
   gitlab_rails['redis_port'] = '6379'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: gitlab-deployment
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: gitlab
   spec:
     containers:
     - name: gitlab-container
       image: gitlab/gitlab-ce:latest
       volumeMounts:
       - name: gitlab-volume
         mountPath: /etc/gitlab
     volumes:
     - name: gitlab-volume
       configMap:
         name: gitlab-configmap
     nodeSelector:
       TypeOfPod: GitLab
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-service
spec:
  type: NodePod
  selector:
    app: gitlab
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30090
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30100
  - name: ssh
    protocol: TCP
    port: 2222
    targetPort: 22
