kind: Service
apiVersion: v1
metadata:
  name: gitlab-service
spec:
  selector:
    app: gitlab
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  - name: https
    protocol: TCP
    port: 4433
    targetPort: 443
  - name: ssh
    protocol: TCP
    port: 2222
    targetPort: 22
  externalIPs:
    - 10.25.25.130
    - 10.25.25.110
#Expose les IPs sur les nodes ou les pod tourne
