apiVersion: v1
kind: ConfigMap
metadata:
 name: gitlab-configmap
data:
 # property-like keys
 gitlab-rb-file-name: gitlab
 # file-like keys
 gitlab: |
   # Disable the built-in Postgres
   postgresql['enable'] = false
   # Fill in the connection details for database.yml
   gitlab_rails['db_adapter'] = 'postgresql'
   gitlab_rails['db_encoding'] = 'utf8'
   gitlab_rails['db_host'] = 'postgresql-deployment'
   gitlab_rails['db_port'] = '5432'
   gitlab_rails['db_username'] = 'postgres'
   gitlab_rails['db_password'] = 'superpostgres'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: configmap-gitlab-deployment
 labels:
   name: configmap-gitlab-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     name: configmap-gitlab
 template:
   metadata:
     labels:
       name: configmap-gitlab
   spec:
     containers:
     - name: gitlab-container
       image: gitlab/gitlab-ce:latest
       #command: [ "game-server", "--config-dir=/etc/game/cfg" ]
       volumeMounts:
       - name: config-volume-gitlab
         mountPath: /etc/gitlab/
     volumes:
     - name: config-volume-gitlab
       configMap:
         name: gitlab-configmap
         items:
         - key: gitlab-rb
           path: gitlab.rb
     nodeSelector:
       TypeOfPod: GitLab
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-service
spec:
  selector:
    name: configmap-gitlab
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: ssh
    protocol: TCP
    port: 2222
    targetPort: 22
  externalIPs:
    - 10.25.25.100
