apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: gitlab-deployment
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: gitlab
   spec:
     containers:
     - name: gitlab-container
       image: gitlab/gitlab-ce:latest
       volumeMounts:
       - name: gitlab-volume
         mountPath: /var/opt/gitlab
     volumes:
     - name: gitlab-volume
       glusterfs:
         endpoints: gluster-service
         path: /gluster-fs-volume
         readOnly: false
     nodeSelector:
       TypeOfPod: GitLab
