apiVersion: v1
kind: Pod
metadata:
  name: gitbucket-pod
  labels:
    app: gitbucket
spec:
  containers:
  - name: gitbucket-container
    image: f99aq8ove/gitbucket
    ports:
    - containerPort: 8080
      name: http
    - containerPort: 29418
      name: ssh
