apiVersion: v1
kind: Pod
metadata:
  name: gitlab-pod
  labels:
    app: gitlab
spec:
  containers:
  - name: gitlab-container
    image: gitlab/gitlab-ce:latest
    readinessProbe:
      httpGet:
        path: /index.php
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
