apiVersion: v1
kind: Pod
metadata:
  name: gitlab-pod
  labels:
    app: gitlab
spec:
  containers:
  - args:
    - run
    image: gitlab/gitlab-ce:latest
    imagePullPolicy: Always
    name: gitlab-container
  restartPolicy: Always
