apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: htdocs
      mountPath: /usr/share/nginx/html
    readinessProbe:
      httpGet:
        path: /ready.html
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3

  volumes:
  - name: htdocs
    hostPath:
      path: /tmp/htdocs
