apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: rocketchat-deployment
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: rocketchat
   spec:
     containers:
     - name: rocketchat-container
       image: rocket.chat
       env:
       - name: ROOT_URL
         value: http://k8siri.hopto.org/rocket
       - name: MONGO_URL
         value: mongodb://mongo-service/rocketchat
       volumeMounts:
       - name: rocketchat-volume
         mountPath: /tmp
     volumes:
     - name: rocketchat-volume
       glusterfs:
         endpoints: gluster-service
         path: /volume-RocketChat
         readOnly: false


#       readinessProbe:
#         httpGet:
#           path: /rocket/index.php
#           port: 3000
#         initialDelaySeconds: 30
#         periodSeconds: 30
#     nodeSelector:
#       TypeOfPod: rocketchat
