kind: Service
apiVersion: v1
metadata:
  name: rocketchat-service
spec:
  selector:
    app: rocketchat
  ports:
  - name: rocketchathttp
    protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
  type: NodePort
