apiVersion: v1
kind: Pod
metadata:
  name: gluster-2-pod
  labels:
    app: gluster-2
    serv: gluster-srv
spec:
  containers:
  - name: gluster-2-container
    image: clementgiaime/glusterfs:3.10
    imagePullPolicy: Always
    ports:
    - containerPort: 111
      protocol: UDP
    - containerPort: 111
    - containerPort: 24007
    - containerPort: 24008
    - containerPort: 49152
    - containerPort: 49153
    - containerPort: 49154
    - containerPort: 49155
    - containerPort: 49156
    - containerPort: 49157
    - containerPort: 49158
    - containerPort: 49159
    - containerPort: 49160
    volumeMounts:
    - name: mount-gitbucket
      mountPath: /srv/gluster/GitBucket
    - name: mount-mongo
      mountPath: /srv/gluster/Mongo
    - name: mount-postgresql
      mountPath: /srv/gluster/PostgreSQL
    - name: mount-redis
      mountPath: /srv/gluster/Redis
    - name: mount-gitlab
      mountPath: /srv/gluster/GitLab
    securityContext:
        capabilities:
          add:
            - SYS_ADMIN
            - MKNOD
  volumes:
  - name: mount-gitbucket
    hostPath:
      path: /srv/gluster/GitBucket
  - name: mount-mongo
    hostPath:
      path: /srv/gluster/Mongo
  - name: mount-postgresql
    hostPath:
      path: /srv/gluster/PostgreSQL
  - name: mount-redis
    hostPath:
      path: /srv/gluster/Redis
  - name: mount-gitlab
    hostPath:
      path: /srv/gluster/GitLab
  nodeSelector:
    TypeOfPod: gluster-2
