apiVersion: v1
kind: Pod
metadata:
  name: gluster-1-pod
  labels:
    app: gluster-1
    serv: gluster-srv
spec:
  containers:
  - name: gluster-1-container
    image: clementgiaime/glusterfs:3.10
    imagePullPolicy: Always
    ports:
    - containerPort: 111
      protocol: UDP
    - containerPort: 111
    - containerPort: 24007
    - containerPort: 24008
    - containerPort: 49152
    - containerPort: 49153
    - containerPort: 49154
    - containerPort: 49155
    - containerPort: 49156
    - containerPort: 49157
    - containerPort: 49158
    - containerPort: 49159
    - containerPort: 49160
    volumeMounts:
    - name: gluster-volume
      mountPath: /srv/gluster
    securityContext:
        capabilities:
          add:
            - SYS_ADMIN
            - MKNOD
  volumes:
  - name: gluster-volume
    hostPath:
      path: /srv/gluster
  nodeSelector:
    TypeOfPod: gluster-1
