kind: Service
apiVersion: v1
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
  - name: mongodatabase
    protocol: TCP
    port: 27017
    targetPort: 27017
  externalIPs:
    - 10.25.25.100
