apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: mongo-deployment
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: mongo
   spec:
     containers:
     - name: mongo-container
       image: mongo
#     nodeSelector:
#       TypeOfPod: mongo
       volumeMounts:
       - name: mongo-volume
         mountPath: /data/db
     volumes:
     - name: mongo-volume
       glusterfs:
         endpoints: gluster-cluster
         path: /gluster-fs-volume
         readOnly: false
