apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: redis-deployment
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: redis
   spec:
     containers:
     - name: redis-container
       image: redis
       volumeMounts:
       - name: redis-volume
         mountPath: /data
     volumes:
     - name: redis-volume
       glusterfs:
         endpoints: gluster-service
         path: /volume-Redis
         readOnly: false
